apiVersion: v1
kind: Secret
metadata:
  name: checkout-db
  labels:
    app.kubernetes.io/name: checkout-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: Opaque
stringData:
  DATABASE_URL: postgres://checkout:demo@postgres.payments.svc.cluster.local:5432/checkout
